CMakeLists.txt, src/map.cc, src/sfall_config.h, src/tile.cc, src/tile.h, src/tile_hires_stencil.cc, src/tile_hires_stencil.h
https://github.com/alexbatalov/fallout2-ce/pull/427
=> Add tile hires stencil

src/file_find.cc
That a forward port of https://github.com/alexbatalov/fallout1-ce/pull/119 from fallout-ce
=> Fix broken game load/save on Linux due to case sensitive opendir()

src/input.cc, src/inventory.cc
Fixes warnings from Clang-format.
=> Fixes for 2 Merged `y0lo`'s PRs

src/character_editor.cc
https://github.com/alexbatalov/fallout2-ce/pull/432
=> Fix wrong variable usage in character_editor

.github/workflows/ci-build.yml
Fixes wrong check in my previous PR.
=> Fix for workflow file

src/game_sound.cc
https://github.com/alexbatalov/fallout2-ce/pull/436
=> Fix no sound issue

src/automap.cc, src/elevator.cc, src/game.h, src/game_mouse.cc, src/inventory.cc, src/loadsave.cc, src/mainmenu.cc, src/mouse.cc, src/options.cc, src/pipboy.cc, src/preferences.cc, src/skilldex.cc, src/touch.cc, src/touch.h, src/worldmap.cc
Long story short: makes game switch between two control styles (Mouse style & Touchscreen style) in big part of menus.
Also adds these features:
1. Adds finger scrolling for inventory.
2. Adds touchscreen mode for walking
=> Improved touchscreen controls

src/main.cc
=> Fix background music not being stopped when playing intro in mainmenu

src/skill.cc
Fixes the incorrect message when attempting to repair robots.
=> Update skill.cc repair robot message

.github/workflows/ci-build.yml
- Update apk file name
- Move sleep into own step
=> Fix ci release names

.github/workflows/ci-build.yml
Just to check what clang-format version we use
=> Show clang-format version in CI run

.github/workflows/ci-build.yml
To make CI check pass if one is tired of annoying formatting issues
=> Add label to ignore clang format check

.github/workflows/ci-build-web.yml, .github/workflows/ci-delete-pr-preview.yml
This PR adds a preview build for pull requests.
Due to security reasons it works only if PR is opened from branch from this repository. If it is a PR from fork then it will not deploy a preview (an example here https://github.com/fallout2-ce/fallout2-ce/pull/96)
Having this should make it easier to test opened PRs
=> Add preview builds (from this repo branch)

.github/workflows/ci-build-web.yml, .github/workflows/ci-delete-pr-preview.yml
Add webassembly preview builds
=> Add preview builds

.github/workflows/ci-build.yml
Just to be able to check how many formatting warnings PR with label have
=> Show formatting warnings if label is present but do not raise error

.github/workflows/ci-build.yml
To fix this https://github.com/fallout2-ce/fallout2-ce/actions/runs/14822792694
=> Do not check PR labels if it is not a pull request

src/loadsave.cc, src/pipboy.cc, src/pipboy.h
Same as https://github.com/fallout2-ce/fallout2-ce/pull/98 but with text from pipboy file.
This is a separate PR just to unblock previous if we still have some hesitations about using pipboy text
=> Update loadsave with pipboy texts

src/tile.cc
Duplicate of https://github.com/fallout2-ce/fallout2-ce/pull/2/ to test
=> Update tile.cc (duplicate)

src/actions.cc, src/actions.h
Zero functional changes were made.  This PR renames function parameters only
=> Deobfucate action.h,cc

src/combat_ai.cc
Duplicate of https://github.com/fallout2-ce/fallout2-ce/pull/65
=> Fixed AI loading single-rounds in magazines (duplicate with preview)

src/animation.cc
Almost entirely renaming three struct fields of `AnimationSad` (an in-progress movement) and adding constants.  Also renamed the one remaining struct field of `AnimationSequence`.
As usual, there are zero functional changes in this PR.
We could also rename `AnimationSad` since it doesn't have much meaning.  It seems to be a movement-relation animation which tracks movement from one tile to another.  I don't have any brilliant ideas for the name, though.
=> Deobfuscate animation.cc

src/loadsave.cc, src/pipboy.cc, src/pipboy.h
Fixes https://github.com/fallout2-ce/fallout2-ce/issues/116
https://github.com/fallout2-ce/fallout2-ce/issues/116#issuecomment-2869647589
=> Load pipboy messages when rendering saveslots

src/pipboy.cc
Adds full pagination to Status, Data and Automaps main and sub pages to prevent overflow.
Brought over from original Fallout 2 CE repository.
=> Update pipboy.cc for full pagination

src/pipboy.cc
Same as https://github.com/fallout2-ce/fallout2-ce/pull/51 but with preview link
=> Update pipboy.cc for full pagination (duplicate)

src/pipboy.cc
Fixes slightly misaligned buttons in the pipboy
Before:
After:
=> fix-pipboy-buttons

src/game.cc, src/game.h, src/window.cc, src/window.h
=> More deobfuscation in `window.cc,h`

sfall_testing/gl_test_stats.ssl
Just to ensure that actions points are re-calculated after updating agility.
Same as in tests readme
=> Add test for derived stats

sfall_testing/gl_test_misc.ssl, src/sfall_opcodes.cc
Pretty simple one; it's useful to do some easy ones as I get used to the codebase and ssl scripting
=> Add `toggle_active_hand` (sfall)

src/sfall_metarules.cc, src/sfall_opcodes.cc
Silence newly-added build warnings.  Not trying to fix the ones in existing fallout source.
=> Fix build warnings introduced by sfall opcodes/metarules

.github/workflows/ci-build-web.yml, .github/workflows/ci-delete-pr-preview.yml
Fixes https://github.com/fallout2-ce/fallout2-ce/issues/241
=> Use deployment action instead of comment

.github/workflows/ci-delete-pr-preview.yml
=> Fix deployments cleanup
