fallout2-ce/fallout2-ce

- src/combat.cc
In some cases function `calledShotSelectHitLocation` can return not a `-1` value but not to set `hitLocation`. This causes undefined behavior when `hitLocation` is used later, and it can cause the game to crash with segfault because `hitLocation` is used as array index later.
This PR ensures that if `calledShotSelectHitLocation` function reports a success then `hitLocation` value will always be set
Originally reported in https://www.nma-fallout.com/threads/fallout-nevada-and-sonora-in-the-browser.222617/#post-4529005
> Set hitLocation when return status is not -1

- src/combat.cc
- src/input.cc
https://github.com/alexbatalov/fallout2-ce/pull/308
Issue: if a user skips turn by clicking end a combat turn button the cursor becomes frozen in "watch" mode but all input events are queued. If a user clicked while the AI turn is not ended then the next user's turn is skipped.
Fix: clear input queue each time before user's turn.
> Clear input envents on combat turn

- .gitignore
- CMakeLists.txt
- cmake/gitver.cmake
- src/game.cc
- src/mainmenu.cc
- src/platform/git_version.h.in
- src/version.h
Makes engine display some info about itself.
1. Commit hash that was used as source for code.
2. Date, when commit was made.
> Engine versioning

- src/art.cc
- src/character_editor.cc
src/character_editor.cc 7253 err V783 Dereferencing of the invalid iterator 'gCustomKarmaFolderDescriptions.end()' might take place.
src/art.cc 636 err V781 The value of the 'type' variable is checked after it was used. Perhaps there is a mistake in program logic. Check lines: 636, 640.
src/art.cc 528 err V547 Expression is always false.
https://github.com/alexbatalov/fallout2-ce/issues/433
> Pvs studio fixes

- src/game.cc
The 1-st color always must be black, but never does in F2 splashes. This makes background renders as white.
> Runtime fix of Splashes wrong pal

- .github/workflows/ci-build.yml
- CMakePresets.json
- src/interface.cc
- src/platform_compat.cc
- src/text_object.cc
This PR is done via vibe coding
Additionally, this PR changes CI checks into Release mode (for Windows only) because debug versions needs `MSVCP140D.dll`
> Add Windows XP x86 support

- src/animation.cc
It's annoying to see a place you can walk to but still get the hex 'x' because path expansion exhausted limited node capacity. Increased memory usage and execution time are non-issues on modern and even non-modern systems by today's standards.
> QoL: increased node expansion while pathing

- .github/workflows/ci-build.yml
This PR adds platforms and architecture suffix to binary files.
Currently in the release we have `$folder-$name` files:
This PR changes it just to be `$file` which should be unique now
> Fix CI release file names

- src/loadsave.cc
Small fix to Load/Save descriptions in the info box.
Allows for longer names, and wraps them to second line if they are too long.
See this screenie (ignore garbled thumbnail - unrelated)
> Update loadsave.cc to fit longer location names in Infobox

- .github/workflows/ci-build-web.yml
Right now web interface builds failing. This PR adds a last working commit for web UI.
Revert this PR when web UI issue is fixed
> Temp workaround: add commit hash for web interface

- src/combat_ai.cc
IIRC, the "unit" for things like 10mm ammo in F1 used to be a dozen (12x). In F2CE, the unit of ammo seems to be a single round. Prior to this patch, AI companions (in my case, the Mercenary in Sonora) would reload a single round into their weapon when they run out, so turns in combat become a loop of fire, reload, fire, reload, etc.
With this patch, AI reloading keeps inserting ammo into the weapon until capacity is reached or the critter runs out of ammo.
> Fixed AI loading single-rounds in magazines.

- src/map.cc
Fixes #115
Clear floating text on other types of transitions
See issue details
If you want to test in depth, making the text last a lot longer is helpful:
```
diff --git a/src/text_object.cc b/src/text_object.cc
index a851c8e..03fb276 100644
--- a/src/text_object.cc
+++ b/src/text_object.cc
@@ -335,7 +335,7 @@ static void textObjectsTicker()
for (int index = 0; index < gTextObjectsCount; index++) {
TextObject* textObject = gTextObjects[index];
-        unsigned int delay = gTextObjectsLineDelay * textObject->linesCount + gTextObjectsBaseDelay;
+        unsigned int delay = gTextObjectsLineDelay * textObject->linesCount + gTextObjectsBaseDelay*10;
if ((textObject->flags & TEXT_OBJECT_MARKED_FOR_REMOVAL) != 0 || (getTicksBetween(_get_bk_time(), textObject->time) > delay)) { …
```
> Remove floaters when moving to a new world map location

- src/inventory.cc
Fixed to make buttons work when clicked, or when using key commands.
This makes an imperfect button sound (misses the click release), however, the game is littered with this compromise.
Fixs #88
> Update inventory.cc to fix button click sounds for 'Move Items'

- README.md
- src/game_dialog.cc
- src/inventory.cc
- src/pipboy.cc
Ctrl-click does a "fast move" of item when the destination is obvious, meaning you don't have to drag it.  This is especially helpful if you have multiple things to move (in practice this is one reason why `Take All` was added in F2)
Ctrl-click will automatically move the entire stack, so it's also a way of avoiding the item quantity screen.  The exception to this is when moving money in the barter screen, in which case the amount moved is the amount needed to balance the trade (this is much more useful than moving your entire stack of money).  In the future, we could add something like Ctrl-Shift-click for moving a single item from a stack.  
Barter: move from table (offer) to inventory and back, on both merchant and pc.
Looting/stealing: move from one side to the other.
Inventory: …
> QoL: Add Ctrl-click to move items in inventory, barter, looting/stealing

- src/inventory.cc
Fixes #160 
Conditional was incorrect. Searched around for the correct setting for 'quantity', found that, used it, and the inventory 'moving' of items seems to be working correctly now.
> Inventory Item not Disappearing Fix

- src/inventory.cc
Most other button make a sound when you use the keyboard shortcut, and so ought these.
Loot a container and type `a`.  Or move a >1 qty stack, and type `a`
> Add click when using `a` to `Take all` or move `All`

- src/interface.cc
A different fix for https://github.com/alexbatalov/fallout2-ce/pull/364
Use a custom interface bar (usually 800px), with screen width >640 but smaller than 800:
e.g. f2_res.ini
```
[MAIN]
SCR_WIDTH=650
SCR_HEIGHT=480
[IFACE]
IFACE_BAR_WIDTH=800 
```
Without this patch, the game will crash.  With it, it'll just use the normal iface bar
> Don't crash if game resolution is <800 with custom interface bar

- .github/workflows/ci-build.yml
- .github/workflows/release.yml
Github is going to disable our current windows runner
https://github.com/actions/runner-images/issues/12045
So we need to update.
I tried to cache `C:\ProgramData\chocolatey\lib` but then `cmake` fails to understand that `v141_xp` toolset is installed when cache is restored.
I tested Windows x86 build on virtual machine with Windows XP and it started (shows "Failed to load fonts" error)
> Update windows runner

- src/sfall_opcodes.cc
This also makes them significantly easier to find sfall opcode implementations in the codebase.
Note: the vanilla opcode implementations are in camelCase.  I don't think we necessarily need to change those since they are unlikely to be worked on frequently.
> Rename sfall opcodes to use underscores for consistency.

- .github/workflows/ci-build-web.yml
- .github/workflows/ci-delete-pr-preview.yml
Fetching this repo takes some time because of `gh-pages` branch which holds all history of deployments. In this PR I am trying to use single-commit option to reduce checkout size.
Let's hope it will not break preview deployments
> Add single-commit option for preview deployments

- README.md
- src/interface.cc
(still can be overriden by config)
Will fall back to 640px version if screen is narrower than 800px or asset doesn't exist
> Default to 800px interface bar

- sfall_testing/gl_test_arrays.ssl
- sfall_testing/gl_test_stats.ssl
- sfall_testing/test_utils.h
This PR uses global variables and arrays for testing, so it will show full summary in float message.
To reset tests stats after reload this PR uses arrays
Copy all `.int` files from `sfall_testing` folder and run the game
> Use global variables and arrays to show tests summary

- sfall_testing/gl_test_ini.ssl
- sfall_testing/test.ini
- sfall_testing/test_utils.h
- src/interpreter.cc
- src/interpreter.h
- src/sfall_ini.cc
- src/sfall_ini.h
- src/sfall_metarules.cc
- src/sfall_opcodes.cc
Implements `get_ini_section`, needed for Et Tu, and `get_ini_sections`.  Fixes buggy `set_ini_setting`.  
Also includes tests for existing ini functions, and moves them all to `sfall_init.cc`.   (opcodes and metarules files were getting long, and this matches sfall's structure)
Test using the gl_test script.  You'll also need `test.ini` in the game folder
> sfall: `get_ini_section(s)`

- src/inventory.cc
Ctrl-click to equip in inventory screen:
1. Armor gets equipped to the armor slot
2. Any other item gets equipped to the first free hand slot, or the left hand if both are occupied 
Continues missing work from:
https://github.com/fallout2-ce/fallout2-ce/pull/133
This is very similar to the sfall feature.
> QoL: Ctrl-click to equip in inventory screen

- sfall_testing/gl_test_worldmap.ssl
- src/sfall_opcodes.cc
- src/worldmap.cc
- src/worldmap.h
No unittest for this one, but added a script for manual testing.
I inverted the travel time calculation since it was a bit confusing.  It now more closely matches sfall: https://github.com/sfall-team/sfall/blob/0e2317fd4c8b2eca4be11add377c6776f07c6354/sfall/Modules/Worldmap.cpp#L220
This is used by Et Tu
> (sfall) Implement `set_map_time_multi`

- sfall_testing/gl_test_metarule_exists.ssl
- src/interpreter.cc
- src/interpreter.h
- src/sfall_metarules.cc
A non-sFall metarule to check if opcode is implemented in `fallout2-ce`.
It is safe to use it in scripts because a call into `metarule_exist` can be done prior to calling `opcode_exists`.
The main use case it to allow modders to skip some part of scripts if something is not implemented yet.
Run tests
> Add opcode_exists metarule

- sfall_testing/gl_test_iface_tag.ssl
- sfall_testing/test_utils.h
- src/interface.cc
- src/interface.h
- src/sfall_opcodes.cc
Implement "interface tags" (called "indicators" in the code): https://sfall-team.github.io/sfall/tags/
This is all that is used by RPU (absent partycontrol mod)
Does *not* implement custom tags, yet.  That's a little more involved.
> Implement `show/hide_iface_tag,is_iface_tag_active` for vanilla tags

- sfall_testing/gl_test_message_box.ssl
- src/dbox.cc
- src/dbox.h
- src/sfall_metarules.cc
This is used by Et Tu and RPU.
Also: some decryption of the underlying dialog box code
Use the included test script
> `message_box` metarule

- src/game_mouse.cc
Fixes #226
Cursor is missing when using context menu on an object at the far right side of the screen (see screenshot in issue)
Hover over an item right next the right side of the screen, and long-left-click
Fixed:
Reviewer's note: the bugfix is in the first commit—it might be easier to review just that commit.
Originally reported and fix in fallout1-ce here: https://github.com/alexbatalov/fallout1-ce/pull/221
> Fix missing cursor on the right (mirrored) context menu

- src/art.cc
- src/interpreter_extra.cc
- src/inventory.cc
- src/obj_types.h
Introduces FID_WEAPON_CODE and FID_ROTATION.  In future PRs we can use these to eliminate a lot of inlined bit shifts
> Deobfuscate one function in interpreter_extra.cc

- src/game_sound.cc
Small fix to be able to re-load game when compiled with address sanitizer
Compile with sanitizer, load game, load game again
> Do not copy the same string, prevent sanitizer crash

- src/map.cc
This fixes https://github.com/alexbatalov/fallout2-ce/issues/501
I compiled it with address sanitizer, and I was able to reproduce `heap-buffer-overflow`
It happens only when game decides to land Dude near hole (not near cave) on the Raiders map.
Take a savefile from the issue above, use gog version, build with sanitizer, enter "unknown", be lucky to get nearby hole (as on screenshot)
> Resize gMapGlobalPointers if inconsistency between .map and .gam file

- src/db.cc
There is a off-by-one error in duplicates cleanup.
Build with sanitizer, use Sonora, unpack all `.dat` files, start the game
> Fix off-by-one error in duplicates cleanup
